### ISSUE TITLE
Whispers misses secret from list

### ISSUE THREAD

**Issue by cosad3s** [adeptex/whispers#97]
**Describe the bug**

Some secret are missed from JSON file.

**To Reproduce**

I have this JSON file:

```json
{"type": "bearer", "bearer": [{"key": "token", "value": "THISISSECRET", "type": "string"}]}
```

I expected to have `bearer` to be detected. I have built this simple config:

```yaml
include:
  rules:
    - id: authorizations
      message: Authorization token
      severity: MAJOR
      group: keys
      key:
        regex: .*(bearer).*$
        ignorecase: true
```

Python code:

```python
import whispers

args = "-c config.yml file.json"

for secret in whispers.secrets(args):
  print(f"[{secret.file}:{secret.line}] {secret.key} = {secret.value}")
```

**No secret is detected / displayed.**

**Expected behavior**

Secret `"key": "token", "value": "THISISSECRET"` detected.

**System information:**

 - OS (name, version): kali
 - Python version: 3.11
 - Whispers version: 2.1.5
